language: python
cache: pip
python:
  # - "2.6" # not supported by the new flake8 (ordereddict)
  - "2.7"
  # - "3.2" # Not supported
  # - "3.3" # Not supported
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
# command to install dependencies
install: "pip install -r dev-requirements.txt"
# command to run tests
script: nosetests
