version: 2
jobs: 
  build:
    working_directory: ~/circleci 
    docker:        
    - image: circleci/python:3          
      environment:
        ROLLBAR_SERVER_KEY: test
    steps: 
      - checkout 
      - restore_cache: 
          key: deps1-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}
      - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt   
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run: # run tests
          command: |
            . venv/bin/activate
            nosetests
